[package]
name = "smolvm-registry"
version = "1.9.2"
edition = "2021"
description = "OCI Distribution client for smolmachines registry"
license = "Apache-2.0"
repository = "https://github.com/smol-machines/smolvm"

[dependencies]
smolvm-pack = { path = "../smolvm-pack", version = "1.6.1" }
h12tiny = { version = "0.1.0", default-features = false, features = ["client", "http1", "http2", "tls", "util"] }
hyper = { package = "laputa-hyper-futures-lite", version = "=1.11.0-beta.0", default-features = false, features = ["client", "http1", "http2"] }
sha2 = "0.10"
bytes = "1"
http = "1"
hex = "0.4"
futures-lite = { workspace = true }
futures-rustls = { version = "0.26", default-features = false, features = ["tls12"] }
rustls = { workspace = true, features = ["std", "tls12"] }
rustls-graviola = "0.4"
rustls-pemfile = { workspace = true }
url = "2"
base64 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
dirs = "5"
filetime = "0.2"
futures-util = { workspace = true }

[dev-dependencies]
tempfile = "3"
